dependencies:
- name: prometheus
  version: "9.1.0"
  repository: https://kubernetes-charts.storage.googleapis.com
- name: grafana
  version: "3.8.9"
  repository: https://kubernetes-charts.storage.googleapis.com